---
title: "STATS 531 Homework 4"
author: "Due Sunday 2/15, 11.59pm"
output: pdf_document
format:
  pdf:
    include-in-header:
      text: |
        \usepackage{fullpage}
---

\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}


_This homework gives you some experience at manipulating models and data in the frequency domain. Submit to Canvas a pdf report and qmd source, together with any other files needed to compile the qmd to pdf. You can assume that the grader already has the file `sunspots.txt`. The homework report will be graded following the grading scheme in the [syllabus](../syllabus.html)._

**Question 4.1**. 

**A**. Compute and plot the spectral density function of a stationary AR2 model,
$$ X_n =  1.5 X_{n-1} - 0.8X_{n-2} + \epsilon_n,$$
where $\{\epsilon_n\}$ is white noise with $\var(\epsilon_n)=\sigma^2$.
You can use software to do this, or carry out some computations analytically. 
It is up to you how much (or little) algebra you choose to work through, but please explain fully how you carried out your calculation.
Also, plot the autocovariance function.

**B**. Compute and plot the spectral density function of an MA(2) moving mean,
$$ X_n = \epsilon_{n-2} + \epsilon_{n-1}+\epsilon_n,$$
where $\{\epsilon_n\}$ is white noise with $\var(\epsilon_n)=\sigma^2$.
As in part (A), you can use software to do this or carry out some computations analytically. 
Also, plot the autocovariance function.

**C**. Comment briefly on what you find in parts A and B.


**Question 4.2**. Estimate a spectral density function for the sunspot time series in [sunspots.txt](sunspots.txt). Comment on your choice of estimator, and discuss comparisons with alternative approaches. Comment on scientific interpretations of the resulting estimate. As statisticians, we may not have domain-specific expertise but we should still try to think and talk about the scientific implications of the statistical inferences. These data, as well as some background on the historical and current interest in sunspot activity, are described at [https://www.sidc.be/SILSO/home](https://www.sidc.be/SILSO/home).

