---
title: "STATS 531 project report format\\vspace{-2cm}"
bibliography: references.bib
output: pdf_document
format:
  pdf:
    include-in-header:
      text: |
        \RedeclareSectionCommand[
          beforeskip=0.5em,
          runin=false,
          afterskip=0em
        ]{section}
        \RedeclareSectionCommand[
          beforeskip=0em,
          runin=false,
          afterskip=0em
        ]{subsection}
        \RedeclareSectionCommand[
          beforeskip=0em,
          runin=false,
          afterskip=0em
        ]{subsubsection}
        \usepackage{fullpage}
number-sections: true
jupyter: python3
---

## Abstract {.unnumbered}

This is the abstract. It should briefly describe the context of the report and highlight the findings of highest interest to the target readers (other students in the class, the GSI, and the instructor). 
Usually, the abstract is 150-300 words.

# Introduction

The [source code](https://github.com/ionides/531w26/tree/main/template) for this document provides a template based on [Quarto](https://quarto.org/) for STATS 531,
We demonstrate `Python` [@perez2011python] code with some discussion of how  `R` [@R-base] code can be included.

# Methods

This section covers basic markdown techniques.

## Formatting

[Quarto](https://quarto.org/) is a versatile  formatting system for authoring HTML based on markdown, integrating LaTeX and various code block interpreted either via Jupyter or Knitr (and thus deal with Python, R and many other langages). It relies on the [Pandoc Markdown](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html) markup language. 

To render/compile a document, run `quarto render`.
A document will be generated that includes both content as well as the output of any embedded code chunks within the document.
To generate `template.pdf`,

``` .bash
quarto render template.qmd 
```

## Basic markdown 

**Bold text** or _italic_

- This is a list
- With more elements
- It isn't numbered.

But we can also do a numbered list

1. This is my first item
2. This is my second item
3. This is my third item

In scientific reports, bullet points are seldom used.

## Mathematics

[LaTeX](https://www.latex-project.org/) code is natively supported, which makes it possible to use mathematical formulae:
$$
f(x_1, \dots, x_n; \mu, \sigma^2) =
\frac{1}{\sigma \sqrt{2\pi}} \exp{\left(- \frac{1}{2\sigma^2}\sum_{i=1}^n(x_i - \mu)^2\right)}
$${#eq-my-first-equation}
It is also posible to cross-reference an equation, see @eq-my-first-equation and @eq-mylabel for examples.
$$
\begin{aligned}
D_{x_N} & = \frac12
\left[\begin{array}{cc}
x_L^\top & x_N^\top \end{array}\right] \,
\left[\begin{array}{cc}  L_L & B \\ B^\top & L_N \end{array}\right] \,
\left[\begin{array}{c}
x_L \\ x_N \end{array}\right] \\
& = \frac12 (x_L^\top L_L x_L + 2 x_N^\top B^\top x_L + x_N^\top L_N x_N),
\end{aligned}
$${#eq-mylabel}

Numbering and cross-referencing makes your report easier to read and easier to peer review. That is a consideration for good scholarship


# Results

A reproducible document should not contain hard-coded results. 
Instead, it should run code to generate these results from data.
Quarto uses either Jupyter or knitr to render code chunks. 
This can be triggered in the yaml header, e.g., for Jupyter (should be installed on your computer) use

``` yaml
---
title: "My Document"
author "Jane Doe"
jupyter: python3
---
```

Here, we use Jupyter with Python. As an example of a simple `Python` chunk:
```{python}
#| echo: true
#| label: python-code
import numpy as np
np.random.seed(0)
x = np.random.normal(size=10)
```
Variables can be accessed inline, outside of code chunks, for example, the mean of the variable `x` is `{python} f"{np.mean(x):.3f}"`.

To incorporate some R, called from Python, you can use `%%R` cell magic via the `rpy2` package.
Alternatively, you can run the qmd file via R and include some Python via the `reticulate` package [@R-reticulate].
It may be simplest to use a single language, and here we stick to Python.

## Figures

```{python}
#| echo: true
#| label: fig-x
#| fig-cap: "A time plot of x"
import matplotlib.pyplot as plt
plt.figure(figsize=(8,3))
plt.plot(range(10),x)
plt.tight_layout(); plt.show()
```

Plots can be generated and referenced as shown. See plot @fig-x. 
Usually, we set `echo: false` in the code chunk to suppress the code in the report. 
The qmd source should be available for those who want to check the code.


## Tables

Tables can be generated with markdown as follows.
The label, `@tbl-mylabel`, renders as @tbl-mylabel.

```markdown
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
: my table caption {#tbl-mylabel}
```

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
: my table caption {#tbl-mylabel}

For tabulating results of a data analysis, it is useful to know that Quarto automatically renders the DataFrame as a markdown table when it is the last line of the chunk:

```{python}
#| label: tbl-data-summary
#| tbl-cap: "A summary table of example data."
#| echo: true
import pandas as pd
data = {
    'Fruit': ['Apple', 'Pear', 'Orange'],
    'Price': [2.05, 1.37, 3.09],
    'Quantity': [100, 150, 80]
}

df = pd.DataFrame(data)
df
```

# Conclusions

As well as discussing the main results, this section can include speculative interpretation. 
References are welcome to connect your analysis to the broader literature.

## Bibliographic references

References are displayed using [BibTeX](http://www.bibtex.org/), e.g. `[@computo]` will be displayed as [@computo], where `computo` is the bibtex key for this specific entry.
`@computo` gives an unparenthesized reference to @computo.
The bibliographic information is automatically retrieved from the `.bib` file specified in the header of this document (here:`references.bib`).
Some BibTeX entries relevant to STATS 531 are already in [`references.bib`](https://github.com/ionides/531w26/blob/main/template/references.bib), including @huang22, @notes531, @shumway17.

## Other cross-references

As already (partially) seen, Quarto includes a mechanism similar to the bibliographic references for sections, equations, theorems, figures, lists, etc.
Have a look at [this page](https://quarto.org/docs/authoring/cross-references.html).
For example, you may want to cross-reference to the supplementary material (@sec-supp).

## Acknowledgments {.unnumbered}

 This template builds on a template document by [Shao-Ting Chiu](https://github.com/stevengogogo/neurips-quarto-extension/).
 AI was used for debugging via Google AI overview.
Vscode with the Quarto extension was used for editing.

## Bibliography {.unnumbered}

::: {#refs}
:::

# Supplementary material {#sec-supp}

You can put additional analysis here, or other relevant material.
You should not assume the reader will read the supplement systematically.
Material in the supplement should support claims made in the body of the report, and should be referenced in the report.
The strongest and most critical evidence should be in the body of the report, not in the supplement.
