---
title: "STATS 531 Homework 8\\vspace{-3cm}"
output: pdf_document
format:
  pdf:
    header-includes:
      - \usepackage{titling}
      - \pretitle{\begin{center}\vspace{-2cm}\LARGE}
    include-in-header:
      text: |
        \usepackage{fullpage}
	
---


_Due Sunday 4/12_ 

## Preliminary final project results

* Data analysis is an iterative process. Creating a model and fitting it to data, followed by diagnostic analysis, often leads to an improved model.

* To make sure that you have time to get deeper into your data analysis for the final project, this homework assignment requests you to submit a provisional analysis. This should include:

1. The source of the data.

2. A model, written in math and implemented in source code.

3. Preliminary results for simulation, filtering, and searching both locally and globally for a maximum likelihood estimate.

**You do not have to do any writing beyond a few words of explanation. Your homework submission does not have to explain in detail the model and analysis presented. You do not need references, so there is no scholarship component to this homework. Your results do not have to be reproducible from submitted materials. All those things will be included for the final project report.**

* The grade for Homework 8 will be assigned for presenting evidence showing completion of the preliminary steps 1--3 described above.

* Please submit your work as a pdf file. You should collaborate with your final project team, and you can use any other source. However, any results you present should have been run by you even if the code is shared. That is to avoid a situation where only one person in the team knows how to run the code. 

* For your final project, following up on your report for this homework, you can further investigate your model by methods including likelihood ratio tests and profile confidence interval construction. The scientific properties of the fitted model can be studied. You are advised to carry out computations in good time, in case there are delays due to bugs or access to greatlakes. The final project deadline cannot be postponed because we must keep to schedule for the subsequent peer review. 






