
```{python}
#| label: q1_03_nyc_injuries_timeplot
#| echo: false
#| fig-width: 5
#| fig-height: 2.5
#| warning: false
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller

# Read and process data
# Code adapted from
# https://ionides.github.io/531w24/midterm_project/project01/blinded.html
Collision_data = pd.read_csv("data/nyc_motor_collision_injuries.csv", skiprows=4)
Collision_data['date'] = pd.to_datetime(Collision_data['date'], format="%m/%d/%Y")
Collision_data = Collision_data[(Collision_data['date'] >= '2013-01-01') &
                                  (Collision_data['date'] < '2024-01-01')]

# Group by year and month
monthly_data = (Collision_data
    .assign(year=Collision_data['date'].dt.year,
            month=Collision_data['date'].dt.month)
    .groupby(['year', 'month'])['person_injured']
    .sum()
    .reset_index()
)
monthly_data['date'] = pd.to_datetime(monthly_data[['year', 'month']].assign(day=1))
monthly_data = monthly_data[['date', 'person_injured']]

# Plot
fig, ax = plt.subplots(figsize=(5, 2.5))
ax.plot(monthly_data['date'], monthly_data['person_injured']/1000, linewidth=1)
ax.set_xlabel('Year')
ax.set_ylabel('injuries (thousands)')
ax.xaxis.set_major_locator(plt.matplotlib.dates.YearLocator())
ax.xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter('%Y'))
plt.tight_layout()
plt.show()
```


```{python}
#| label: q1_03_adf_for_nyc
#| eval: true
#| echo: false
#| warning: false
#| output: false
result = adfuller(monthly_data['person_injured'],maxlag=4,regression='ct', autolag=None)
print(f"data:  monthly_data['person_injured']")
print(f"Dickey-Fuller = {result[0]:.4f}, Lag order = {result[2]}, p-value = {result[1]:.4f}")
print(f"Alternative hypothesis: stationary")
```

Above are monthly injuries from motor vehicle collisions in New York City. An augmented Dickey-Fuller test, `adfuller(injuries)`, gives a p-value of `"{result[1]:4f}"`. Which is the best way to proceed:

A: The time plot indicates a non-constant mean function describing a major dip due to the COVID-19 pandemic and an increasing trend at other times. The ADF test does not support or refute that model.

B: The ADF test suggests the series is stationary, supporting a decision to fit a SARMA model.

C: The ADF test suggests the series is non-stationary; it should be differenced before fitting a SARMA.

D: The ADF test indicates that the series is non-stationary, supporting the use of a non-constant mean function to describe a major dip due to the COVID-19 pandemic and an increasing trend at other times.


