---
title: "Bjornstad & Grenfell (2001)"
author: "STATS 631, Winter 2026"
format:
  beamer:
    header-includes: |
      \setbeamertemplate{footline}[page number]
    fig_crop: false
---

## Impact

Bjørnstad, O. N., & Grenfell, B. T. (2001). Noisy clockwork: time series analysis of population fluctuations in animals. Science, 293(5530), 638-643. https://doi.org/10.1126/science.1062226.

* cited 763 times


## Concluding challenges

1. both measurement and process stochasticity

2. mechanistic modeling of covariates

3. continuous-time models

4. effective dimension of field data

5. unobserved variables

6. spatiotemporal dynamics


## Context

* 1990s advances in Monte Carlo methods had promise but substantial limitations. They proved insufficient to solve the challenges.

* Deterministic nonlinear dynamics provided candidate mathematical theory for population dynamics, but substantial stochasticity makes that of limited relevance.


## Extra-demographic variation

(p 639, bottom left)

* Log scale variation inconsistent with Poisson and binomial variability


## Wild populations

* Need long-term data, ideally including experimentation

* The (Long Term Ecological Research Network](https://en.wikipedia.org/wiki/Long_Term_Ecological_Research_Network) aims to provide this.


## Since 2001

* What are the main advances (methodological and/or scientific) on this topic over the past 25 years?



