
```{r read_mers,echo=FALSE,fig.width=7,fig.height=2.5,out.width="5in",}
# code adapted from
# https://ionides.github.io/531w24/final_project/project15
mers_df <- read.table(file="data/mers.csv",sep=",",header=TRUE)
saudi <- mers_df[mers_df$Region=='Saudi Arabia',]
mers <- saudi$New.Cases
year <- saudi$Year + (saudi$Week-1)/52
mers <- mers[year>2013.5]
year <- year[year>2013.5]
arma22 <- arima(mers,order=c(2,0,2))
par(mai=c(0.5,1,0.35,0.1))
par(mfrow=c(1,2))
plot(year,mers, type="l", col="black", ylab="MERS Reports", xlab="Year",)
mtext("A",side=3,line=0,at=2012.1,cex=2)
qqnorm(resid(arma22))
qqline(resid(arma22))
mtext("B",side=3,line=0,at=-4.2,cex=2)

```

\(A) Weekly cases of Middle East Respiratory Syndome (MERS) in Saudi Arabia. (B) a normal quantile plot of the residuals from fitting an ARMA(2,2) model to these data using `arima()`. What is the best interpretation of (B)?

A: We should consider fitting a long-tailed error distribution, such as the t distribution.\
B: The model is missing seasonality, which could be critical in this situation.\
C: For using ARMA methods, these data should be log-transformed to make a linear Gaussian approximation more appropriate.\
D: The normal quantile plot shows a long-tailed distribution, but this is not a major problem. We have over 300 data points, so the central limit theorem should hold for parameter estimates.\
E: The normal quantile plot shows long tails, but with the right tail noticeably longer than the left tail. We should consider an asymmetric error distribution.\
F: We should not interpret (B) before testing for stationarity. First run `adf.test()` and, if the null hypothesis is not rejected, recalculate (B) when fitting to the differenced data. 







