---
title: "Midterm 2, STATS 531/631 W26"
author: "In class on 4/15"
format:
  pdf:
    pdf-engine: xelatex
    toc: false
jupyter: python3
---

```{python}
#| echo: false
ALL = True
EXAM = False
#EXAM = True
if EXAM:
    ALL = False
```



\newcommand\exam[1]{#1}
<!-- \renewcommand\exam[1]{} to remove exam formatting -->
\renewcommand\exam[1]{}


<!---
Note: tmp*.qmd files are generated by running:
python generate_questions.py
before rendering this document
--->



\newcommand\var{\mathrm{Var}}
\newcommand\varSample{\mathrm{var}}
\newcommand\cov{\mathrm{Cov}}
\newcommand\covSample{\mathrm{cov}}
\newcommand\cor{\mathrm{Cor}}
\newcommand\corSample{\mathrm{cor}}

\exam{\vspace{1.5cm}

\textbf{Name: \hspace{6cm} UMID:}

\vspace{1.5cm}

}

```{python}
#| output: asis
#| echo: false
#| eval: true
if ALL:
    print("**This document produces different random tests each time the source code generating it is run. The actual midterm will be a realization generated by this random process, or something similar.**")
```

```{python}
#| output: asis
#| echo: false
#| eval: true
if ALL:
    print("**This version lists all the questions currently in the test generator. The actual test will have one question sampled from each of the 6 question categories.**")
```

**Instructions. The test is closed book, and you are not allowed access to any notes. Any electronic devices in your possession must be turned off and remain in a bag on the floor.**

**For each question, circle one letter answer and provide some supporting reasoning.**


\exam{\newpage}

### Q1. Foundations of POMP models

{{< include tmp1.qmd >}}

\exam{\newpage}

### Q2. Likelihood evaluation; the particle filter

{{< include tmp2.qmd >}}

\exam{\newpage}


### Q3. Likelihood maximization; iterated filtering

{{< include tmp3.qmd >}}

\exam{\newpage}

### Q4. Data analysis: epidemiological models

{{< include tmp4.qmd >}}

\exam{\newpage}

### Q5. Data analysis: financial models

{{< include tmp5.qmd >}}

\exam{\newpage}

### Q6. Computing with POMP models

{{< include tmp6.qmd >}}


\exam{\vfill}

------



License: This material is provided under a [Creative Commons license](https://ionides.github.io/531w26/LICENSE)<br>




